In [3]:
import tensorflow as tf
import numpy as np

In [4]:
patch=np.array([[1,2,3],[4,5,6], [7,6,9]], dtype=np.float32)
print patch

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  6.  9.]]


In [5]:
tpatch=tf.constant(patch)

In [43]:
trial=tf.tile(tpatch, [1,3,3,1])

with tf.Session() as sess: 
    print sess.run(trial[:,2:7,2:7,:
                        ])

[[ 9.  7.  6.  9.  7.]
 [ 3.  1.  2.  3.  1.]
 [ 6.  4.  5.  6.  4.]
 [ 9.  7.  6.  9.  7.]
 [ 3.  1.  2.  3.  1.]]


In [41]:
print trial[2:6,2:6]

Tensor("strided_slice_4:0", shape=(4, 4), dtype=float32)
